repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        pass_filenames: false