services:
  app:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/postgres"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data: